[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
vrfy-methods = { path = "../methods" }
bincode = "1.3"
risc0-zkvm = { version = "^2.0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
serde_json = "1.0"
base64 = "0.22.1"